<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
        <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
        <PackageReference Include="MediatR" Version="14.2.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
        <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Cameras\Services\Onvif\Generated\" />
        <Folder Include="Data\Migrations\" />
    </ItemGroup>
    <ItemGroup>
        <None Update="Data\SeedAssets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
