x-project:
  name: sitewatch_container

services:
  database.sitewatch:
    container_name: database.sitewatch
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=SuperStrongPassword1!"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
    ports:
      - "1433:1433"
    user: root
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "SuperStrongPassword1!",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
